name: Build Library

on:
  push:
  pull_request:

jobs:
  build:
    permissions:
        contents: write
        discussions: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Create assets directory
        run: mkdir -p export
    
      - name: Build library
        run: |
          docker buildx build --platform linux/arm64 --load -t libturbojpeg_builder .
          docker run --rm -v ./export:/export -t libturbojpeg_builder
    
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          name: $(date +'%Y%m%d')
          prerelease: false
          draft: false
          files: .export/*
          generate_release_notes: false
